insert into vehicle  (id, name) values (1,'Generic Vehicle');
insert into vehicle  (id, name) values (2,'Mountain Bike');
insert into vehicle  (id, name) values (3,'Simple Bike');
insert into vehicle  (id, name) values (4,'Generic motor vehicle');
insert into vehicle  (id, name) values (5,'Electric Skate');
insert into vehicle  (id, name) values (6,'Generic motor vehicle');
insert into vehicle  (id, name) values (7,'Opel Corsa');
insert into vehicle  (id, name) values (8,'Seat 124');
insert into vehicle  (id, name) values (9,'Boeing 747');
insert into vehicle  (id, name) values (10,'DC-10');
insert into bicycle  (id, gears) values (2, 21);
insert into bicycle  (id, gears) values (3, 1);
insert into motor_vehicle  (id, driving_range) values (4, 100);
insert into motor_vehicle  (id, driving_range) values (5, 50);
insert into motor_vehicle  (id, driving_range) values (6, 100);
insert into motor_vehicle  (id, driving_range) values (7, 50);
insert into motor_vehicle  (id, driving_range) values (8, 50);
insert into motor_vehicle  (id, driving_range) values (9, 500);
insert into motor_vehicle  (id, driving_range) values (10, 400);
insert into car  (id, license, fuel) values (7, '0042GOD', 'Diesel');
insert into car  (id, license, fuel) values (8, '0666EVL', 'Gasoline');
insert into airplane  (id, engines) values (9, 4);
insert into airplane  (id, engines) values (10, 2);
