package es.anaya.spring.data.s03.inheritance;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.CommandLineRunner;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.transaction.annotation.Transactional;
/*
 * create table vehicle (
 * dis varchar(31) not null, 
 * id bigint generated by default as identity, 
 * name varchar(255), 
 * range float, 
 * engines integer, 
 * gears integer, 
 * fuel varchar(255), 
 * license varchar(255), 
 * primary key (id))
 */

@SpringBootApplication
public class Application implements CommandLineRunner {
 
   @Autowired
   VehicleRepository vehicleRepository;

 public static void main(String[] args) {
  SpringApplication.run(Application.class, args);
 }
 
   @Transactional(readOnly = true)
   @Override
   public void run(String... args) throws Exception {

     System.out.println("Showing all vehicle: " 
    		 	+ vehicleRepository.findAll());
     System.out.println("Select by name: " 
    		 	+ vehicleRepository.findByName("Seat 124"));
   }
}

